project:
  type: website
  output-dir: docs
  
website: 
  title: "Yu Lu Homepage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: edu.qmd
        text: Education
      - href: doing.qmd
        text: Progressing
    #  - href: onelayernn.qmd
    #    text: Machine Learning Methods 
format: 
  html: 
    theme: cosmo
    toc: true
